name: pySubstructures
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - seaborn
  - scikit-learn
  - matplotlib
  - plotly
  - loguru
  - jupyterlab
  - ipywidgets
  - pytorch
  - tqdm
  - networkx
  - gensim
  - pip:
    - pymzml==2.4.7
    - mass-spec-utils